#!/usr/bin/env python3
"""
fo-uploader — Upload fo-harvester artifacts to S3-compatible evidence storage.

Generated by ForensicsOperator — constants below are pre-filled with your config.

Two upload modes:
  1. Pre-signed URLs (PRESIGNED_URLS is set) — no boto3, no credentials in script.
     Each URL grants a one-time, time-limited PUT slot for a specific object.
     Up to 3 files can be uploaded (one URL per file slot).
  2. S3 credentials  (ACCESS_KEY / SECRET_KEY are set) — requires boto3.

Usage:
    python fo-uploader.py                      # auto-detect ./output/fo-artifacts-*.zip
    python fo-uploader.py --file evidence.zip  # upload a specific file
    python fo-uploader.py --dir ./output       # scan a directory
    python fo-uploader.py --prefix 2024-IR01   # store under a sub-folder (credentials mode)
"""

from __future__ import annotations

# ── Injected configuration — DO NOT EDIT ─────────────────────────────────────
PRESIGNED_URLS = []  # Pre-signed PUT URLs — one slot per file (preferred, no credentials needed)
MULTIPART_UPLOADS = []  # Pre-provisioned multipart sessions (per file slot) for files > 5 GiB
ENDPOINT = ""  # S3 endpoint hostname (credentials mode)
ACCESS_KEY = ""  # S3 access key        (credentials mode)
SECRET_KEY = ""  # S3 secret key        (credentials mode)
BUCKET = ""  # S3 bucket name       (credentials mode)
REGION = ""  # S3 region            (credentials mode)
USE_SSL = "true"  # "true" / "false"     (credentials mode)
# ─────────────────────────────────────────────────────────────────────────────

import argparse
import glob
import hashlib
import http.client
import ssl
import sys
import urllib.parse
from pathlib import Path

# ── Integrity ─────────────────────────────────────────────────────────────────


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(4 * 1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


# ── Pre-signed URL upload (stdlib only) ───────────────────────────────────────


def _upload_presigned(file_path: Path, url: str) -> str:
    """
    PUT file_path directly to a pre-signed S3 URL.
    No boto3 or third-party libraries needed.
    Returns the SHA-256 hex digest of the uploaded file.
    """
    size = file_path.stat().st_size
    if size > _S3_SINGLE_PUT_MAX:
        raise RuntimeError(
            f"{file_path.name} is {size / 1024 ** 3:.1f} GiB — larger than the 5 GiB single-PUT "
            f"limit. Re-download the uploader from ForensicsOperator for multipart support."
        )
    digest = _sha256(file_path)
    size_mb = size / 1024 / 1024

    print(f"\nUploading {file_path.name} ({size_mb:.1f} MB) via pre-signed URL")
    print(f"  SHA-256 : {digest}")

    parsed = urllib.parse.urlparse(url)
    path_qs = parsed.path + ("?" + parsed.query if parsed.query else "")
    use_ssl = parsed.scheme == "https"

    if use_ssl:
        ctx = ssl.create_default_context()
        conn = http.client.HTTPSConnection(parsed.netloc, context=ctx, timeout=120)
    else:
        conn = http.client.HTTPConnection(parsed.netloc, timeout=120)

    conn.putrequest("PUT", path_qs)
    conn.putheader("Content-Length", str(size))
    conn.putheader("Content-Type", "application/zip")
    conn.endheaders()

    sent = 0
    with open(file_path, "rb") as fh:
        while True:
            chunk = fh.read(4 * 1024 * 1024)
            if not chunk:
                break
            conn.send(chunk)
            sent += len(chunk)
            pct = int(sent * 100 / size) if size else 100
            bar = "#" * (pct // 2) + "-" * (50 - pct // 2)
            print(f"\r  [{bar}] {pct:3d}%", end="", flush=True)

    resp = conn.getresponse()
    resp.read()

    if resp.status not in (200, 204):
        raise RuntimeError(f"Upload rejected: HTTP {resp.status} {resp.reason}")

    print("\n  Uploaded successfully.")
    return digest


# ── Multipart pre-signed upload (stdlib only) ────────────────────────────────
# S3 / Scaleway limits fixed by the API contract: a single PUT accepts at most
# 5 GiB, a part is 5 MiB–5 GiB, and an upload has at most 10 000 parts.
_S3_SINGLE_PUT_MAX = 5 * 1024 * 1024 * 1024  # 5 GiB
_S3_MIN_PART = 5 * 1024 * 1024  # 5 MiB
_S3_MAX_PART = 5 * 1024 * 1024 * 1024  # 5 GiB
_MULTIPART_PREFER_ABOVE = 256 * 1024 * 1024  # 256 MiB


def _abort_multipart(mp: dict) -> None:
    """Best-effort release of an unused/failed multipart session. Never raises."""
    import urllib.request

    abort_url = (mp or {}).get("abort_url")
    if not abort_url:
        return
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    try:
        req = urllib.request.Request(abort_url, method="DELETE")
        with urllib.request.urlopen(req, timeout=60, context=ctx) as r:
            r.read()
    except Exception:
        pass


def _upload_multipart(file_path: Path, mp: dict) -> str:
    """Upload via a pre-provisioned S3 multipart session — the only way to ship
    objects over the 5 GiB single-PUT ceiling, and far more robust on slow links
    (many small, independently-retryable parts uploaded in parallel). Returns
    the SHA-256 hex digest. Aborts the multipart upload on failure."""
    import concurrent.futures
    import socket as _socket
    import time

    size = file_path.stat().st_size
    digest = _sha256(file_path)
    print(f"\nUploading {file_path.name} ({size / 1024 / 1024:.1f} MB) via multipart")
    print(f"  SHA-256 : {digest}")

    part_urls = mp.get("part_urls") or []
    n_slots = len(part_urls)
    complete_url = mp.get("complete_url") or ""
    if not part_urls or not complete_url:
        raise RuntimeError("multipart config is incomplete (missing part/complete URLs)")

    target = int(mp.get("part_size") or (128 * 1024 * 1024))
    part_size = max(target, -(-size // max(1, n_slots)))  # ceil(size / slots)
    part_size = max(_S3_MIN_PART, min(part_size, _S3_MAX_PART))
    num_parts = max(1, -(-size // part_size))  # ceil
    if num_parts > n_slots:
        cap = n_slots * _S3_MAX_PART // (1024 ** 3)
        raise RuntimeError(
            f"file needs {num_parts} parts but only {n_slots} slots were provisioned "
            f"(max ~{cap} GiB); re-download the uploader"
        )
    parallelism = max(1, min(int(mp.get("parallelism") or 4), 8, num_parts))
    part_timeout = min(7200, max(300, part_size // (1024 * 1024)))

    sample = urllib.parse.urlsplit(part_urls[0])
    ctx = None
    if sample.scheme == "https":
        ctx = ssl.create_default_context()
        try:
            with _socket.create_connection(
                (sample.hostname, sample.port or 443), timeout=30
            ) as _s:
                with ctx.wrap_socket(_s, server_hostname=sample.hostname):
                    pass
        except ssl.SSLCertVerificationError:
            ctx = ssl.create_default_context()
            ctx.check_hostname = False
            ctx.verify_mode = ssl.CERT_NONE
        except Exception:
            pass

    def _put_part(part_no):
        offset = (part_no - 1) * part_size
        length = min(part_size, size - offset)
        u = urllib.parse.urlsplit(part_urls[part_no - 1])
        path = u.path + ("?" + u.query if u.query else "")
        last = None
        for attempt in range(1, 6):
            conn = None
            try:
                if u.scheme == "https":
                    conn = http.client.HTTPSConnection(u.netloc, context=ctx, timeout=part_timeout)
                else:
                    conn = http.client.HTTPConnection(u.netloc, timeout=part_timeout)
                conn.putrequest("PUT", path)
                conn.putheader("Content-Length", str(length))
                conn.endheaders()
                with open(file_path, "rb") as fh:
                    fh.seek(offset)
                    remaining = length
                    while remaining > 0:
                        chunk = fh.read(min(4 * 1024 * 1024, remaining))
                        if not chunk:
                            break
                        conn.send(chunk)
                        remaining -= len(chunk)
                resp = conn.getresponse()
                body = resp.read(512)
                if resp.status not in (200, 201):
                    raise RuntimeError(f"HTTP {resp.status}: {body[:200]!r}")
                etag = resp.getheader("ETag") or resp.getheader("Etag")
                if not etag:
                    raise RuntimeError("part response had no ETag")
                return part_no, etag, length
            except Exception as exc:
                last = exc
                if attempt < 5:
                    time.sleep(min(30, 3 * attempt))
            finally:
                if conn is not None:
                    try:
                        conn.close()
                    except Exception:
                        pass
        raise RuntimeError(f"part {part_no} failed after 5 attempts: {last}")

    try:
        etags = {}
        done = 0
        with concurrent.futures.ThreadPoolExecutor(max_workers=parallelism) as ex:
            futs = [ex.submit(_put_part, n) for n in range(1, num_parts + 1)]
            for fut in concurrent.futures.as_completed(futs):
                part_no, etag, length = fut.result()
                etags[part_no] = etag
                done += length
                pct = int(done * 100 / size) if size else 100
                bar = "#" * (pct // 2) + "-" * (50 - pct // 2)
                print(f"\r  [{bar}] {pct:3d}% ({len(etags)}/{num_parts})", end="", flush=True)

        parts_xml = "".join(
            f"<Part><PartNumber>{n}</PartNumber><ETag>{etags[n]}</ETag></Part>"
            for n in range(1, num_parts + 1)
        )
        xml = ("<CompleteMultipartUpload>" + parts_xml + "</CompleteMultipartUpload>").encode()
        u = urllib.parse.urlsplit(complete_url)
        path = u.path + ("?" + u.query if u.query else "")
        if u.scheme == "https":
            conn = http.client.HTTPSConnection(u.netloc, context=ctx, timeout=300)
        else:
            conn = http.client.HTTPConnection(u.netloc, timeout=300)
        conn.putrequest("POST", path)
        conn.putheader("Content-Type", "application/xml")
        conn.putheader("Content-Length", str(len(xml)))
        conn.endheaders()
        conn.send(xml)
        resp = conn.getresponse()
        cbody = resp.read().decode("utf-8", "replace")
        conn.close()
        if resp.status not in (200, 201) or "<Error>" in cbody:
            raise RuntimeError(f"complete failed: HTTP {resp.status}: {cbody[:200]}")
    except Exception:
        _abort_multipart(mp)
        raise

    print("\n  Uploaded successfully.")
    return digest


# ── Credentials-based upload (boto3) ─────────────────────────────────────────


def _build_s3_client():
    try:
        import boto3
    except ImportError:
        print("ERROR: boto3 not installed. Run:  pip install boto3", file=sys.stderr)
        sys.exit(1)

    use_ssl = USE_SSL.lower() in ("true", "1", "yes")
    scheme = "https" if use_ssl else "http"
    ep = ENDPOINT
    for prefix in ("https://", "http://"):
        if ep.lower().startswith(prefix):
            ep = ep[len(prefix) :]
            break
    endpoint_url = f"{scheme}://{ep}" if ep else None

    return boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        aws_access_key_id=ACCESS_KEY,
        aws_secret_access_key=SECRET_KEY,
        region_name=REGION or None,
    )


class _Progress:
    def __init__(self, total: int) -> None:
        self._total = total
        self._seen = 0

    def __call__(self, chunk: int) -> None:
        self._seen += chunk
        pct = int(self._seen * 100 / self._total) if self._total else 100
        bar = "#" * (pct // 2) + "-" * (50 - pct // 2)
        print(f"\r  [{bar}] {pct:3d}%", end="", flush=True)


def _upload_credentials(file_path: Path, bucket: str, key: str, s3) -> str:
    """Upload via S3 credentials. Returns SHA-256 digest."""
    size = file_path.stat().st_size
    digest = _sha256(file_path)
    size_mb = size / 1024 / 1024

    print(f"\nUploading {file_path.name} ({size_mb:.1f} MB)")
    print(f"  → s3://{bucket}/{key}")
    print(f"  SHA-256 : {digest}")

    with open(file_path, "rb") as fh:
        s3.upload_fileobj(fh, bucket, key, Callback=_Progress(size))

    print("\n  Uploaded successfully.")
    return digest


# ── File discovery ─────────────────────────────────────────────────────────────


def _find_artifacts(search_dir: Path) -> list[Path]:
    pattern = str(search_dir / "fo-artifacts-*.zip")
    matches = sorted(glob.glob(pattern))
    if not matches:
        matches = sorted(glob.glob(str(search_dir / "*.zip")))
    return [Path(m) for m in matches]


# ── Entry point ───────────────────────────────────────────────────────────────


def main() -> None:
    presigned_mode = bool(PRESIGNED_URLS)
    creds_mode = bool(ENDPOINT and ACCESS_KEY and SECRET_KEY and BUCKET)

    if not presigned_mode and not creds_mode:
        print(
            "ERROR: Script is not configured. "
            "Download a fresh copy from ForensicsOperator → Collector.",
            file=sys.stderr,
        )
        sys.exit(1)

    parser = argparse.ArgumentParser(
        description="Upload fo-harvester artifacts to S3-compatible evidence storage."
    )
    parser.add_argument(
        "--file",
        metavar="PATH",
        nargs="+",
        action="append",
        help="Files to upload — space-separated or repeated: --file a.zip b.zip",
    )
    parser.add_argument(
        "--dir",
        metavar="DIR",
        default="./output",
        help="Directory to scan for fo-artifacts-*.zip (default: ./output)",
    )
    if not presigned_mode:
        parser.add_argument(
            "--prefix",
            metavar="PREFIX",
            default="",
            help="S3 key prefix (sub-folder inside the bucket)",
        )
    args = parser.parse_args()

    if args.file:
        files = [Path(p) for group in args.file for p in group]
    else:
        files = _find_artifacts(Path(args.dir))
        if not files:
            print(f"No fo-artifacts-*.zip found in {args.dir}/", file=sys.stderr)
            print("Run fo-harvester.py first, or use --file to specify a path.", file=sys.stderr)
            sys.exit(1)

    print("\n─── ForensicsOperator Evidence Uploader ───────────────────────────────")
    if presigned_mode:
        slots = len(PRESIGNED_URLS)
        print(
            f"Mode: pre-signed URLs ({slots} slot{'s' if slots != 1 else ''}, no credentials stored)"
        )
    else:
        print(f"Mode: S3 credentials  →  {ENDPOINT}/{BUCKET}")
    print()

    if presigned_mode:
        slots = len(PRESIGNED_URLS)
        if len(files) > slots:
            print(
                f"WARNING: {len(files)} files found but only {slots} upload slot{'s' if slots != 1 else ''}. "
                f"Extra files will be skipped.",
                file=sys.stderr,
            )
            files = files[:slots]
        for i, (file_path, url) in enumerate(zip(files, PRESIGNED_URLS)):  # noqa: B905 — py3.6 compat
            if not file_path.exists():
                print(f"ERROR: File not found: {file_path}", file=sys.stderr)
                continue
            mp = MULTIPART_UPLOADS[i] if i < len(MULTIPART_UPLOADS) else None
            if mp and file_path.stat().st_size > _MULTIPART_PREFER_ABOVE:
                # Large archive (and anything over the single-PUT ceiling): use
                # the robust parallel multipart path.
                digest = _upload_multipart(file_path, mp)
            else:
                digest = _upload_presigned(file_path, url)
                # Small archive took the single PUT — release the multipart
                # session the server pre-provisioned so it does not orphan.
                if mp:
                    _abort_multipart(mp)
            print("\n  Chain of custody hash  (record this):")
            print(f"  File   : {file_path.name}")
            print(f"  SHA-256: {digest}")
    else:
        import uuid as _uuid

        s3 = _build_s3_client()
        prefix = getattr(args, "prefix", "").strip("/")
        session_uid = _uuid.uuid4().hex[:8]
        for file_path in files:
            if not file_path.exists():
                print(f"ERROR: File not found: {file_path}", file=sys.stderr)
                continue
            base = f"{prefix}/{session_uid}" if prefix else session_uid
            key = f"{base}/{file_path.name}"
            digest = _upload_credentials(file_path, BUCKET, key, s3)
            print("\n  Chain of custody hash  (record this):")
            print(f"  File   : {file_path.name}")
            print(f"  SHA-256: {digest}")

    print("\n───────────────────────────────────────────────────────────────────────")
    print("Done. Go to ForensicsOperator → S3 Triage browser to import into a case.")


if __name__ == "__main__":
    main()
