#!/usr/bin/env python3
"""
fo-uploader — Upload fo-harvester artifacts to S3-compatible evidence storage.

Generated by ForensicsOperator — constants below are pre-filled with your config.

Two upload modes:
  1. Pre-signed URLs (PRESIGNED_URLS is set) — no boto3, no credentials in script.
     Each URL grants a one-time, time-limited PUT slot for a specific object.
     Up to 3 files can be uploaded (one URL per file slot).
  2. S3 credentials  (ACCESS_KEY / SECRET_KEY are set) — requires boto3.

Usage:
    python fo-uploader.py                      # auto-detect ./output/fo-artifacts-*.zip
    python fo-uploader.py --file evidence.zip  # upload a specific file
    python fo-uploader.py --dir ./output       # scan a directory
    python fo-uploader.py --prefix 2024-IR01   # store under a sub-folder (credentials mode)
"""

from __future__ import annotations

# ── Injected configuration — DO NOT EDIT ─────────────────────────────────────
PRESIGNED_URLS = []  # Pre-signed PUT URLs — one slot per file (preferred, no credentials needed)
ENDPOINT = ""  # S3 endpoint hostname (credentials mode)
ACCESS_KEY = ""  # S3 access key        (credentials mode)
SECRET_KEY = ""  # S3 secret key        (credentials mode)
BUCKET = ""  # S3 bucket name       (credentials mode)
REGION = ""  # S3 region            (credentials mode)
USE_SSL = "true"  # "true" / "false"     (credentials mode)
# ─────────────────────────────────────────────────────────────────────────────

import argparse
import glob
import hashlib
import http.client
import ssl
import sys
import urllib.parse
from pathlib import Path

# ── Integrity ─────────────────────────────────────────────────────────────────


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(4 * 1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


# ── Pre-signed URL upload (stdlib only) ───────────────────────────────────────


def _upload_presigned(file_path: Path, url: str) -> str:
    """
    PUT file_path directly to a pre-signed S3 URL.
    No boto3 or third-party libraries needed.
    Returns the SHA-256 hex digest of the uploaded file.
    """
    size = file_path.stat().st_size
    digest = _sha256(file_path)
    size_mb = size / 1024 / 1024

    print(f"\nUploading {file_path.name} ({size_mb:.1f} MB) via pre-signed URL")
    print(f"  SHA-256 : {digest}")

    parsed = urllib.parse.urlparse(url)
    path_qs = parsed.path + ("?" + parsed.query if parsed.query else "")
    use_ssl = parsed.scheme == "https"

    if use_ssl:
        ctx = ssl.create_default_context()
        conn = http.client.HTTPSConnection(parsed.netloc, context=ctx, timeout=120)
    else:
        conn = http.client.HTTPConnection(parsed.netloc, timeout=120)

    conn.putrequest("PUT", path_qs)
    conn.putheader("Content-Length", str(size))
    conn.putheader("Content-Type", "application/zip")
    conn.endheaders()

    sent = 0
    with open(file_path, "rb") as fh:
        while True:
            chunk = fh.read(4 * 1024 * 1024)
            if not chunk:
                break
            conn.send(chunk)
            sent += len(chunk)
            pct = int(sent * 100 / size) if size else 100
            bar = "#" * (pct // 2) + "-" * (50 - pct // 2)
            print(f"\r  [{bar}] {pct:3d}%", end="", flush=True)

    resp = conn.getresponse()
    resp.read()

    if resp.status not in (200, 204):
        raise RuntimeError(f"Upload rejected: HTTP {resp.status} {resp.reason}")

    print("\n  Uploaded successfully.")
    return digest


# ── Credentials-based upload (boto3) ─────────────────────────────────────────


def _build_s3_client():
    try:
        import boto3
    except ImportError:
        print("ERROR: boto3 not installed. Run:  pip install boto3", file=sys.stderr)
        sys.exit(1)

    use_ssl = USE_SSL.lower() in ("true", "1", "yes")
    scheme = "https" if use_ssl else "http"
    ep = ENDPOINT
    for prefix in ("https://", "http://"):
        if ep.lower().startswith(prefix):
            ep = ep[len(prefix) :]
            break
    endpoint_url = f"{scheme}://{ep}" if ep else None

    return boto3.client(
        "s3",
        endpoint_url=endpoint_url,
        aws_access_key_id=ACCESS_KEY,
        aws_secret_access_key=SECRET_KEY,
        region_name=REGION or None,
    )


class _Progress:
    def __init__(self, total: int) -> None:
        self._total = total
        self._seen = 0

    def __call__(self, chunk: int) -> None:
        self._seen += chunk
        pct = int(self._seen * 100 / self._total) if self._total else 100
        bar = "#" * (pct // 2) + "-" * (50 - pct // 2)
        print(f"\r  [{bar}] {pct:3d}%", end="", flush=True)


def _upload_credentials(file_path: Path, bucket: str, key: str, s3) -> str:
    """Upload via S3 credentials. Returns SHA-256 digest."""
    size = file_path.stat().st_size
    digest = _sha256(file_path)
    size_mb = size / 1024 / 1024

    print(f"\nUploading {file_path.name} ({size_mb:.1f} MB)")
    print(f"  → s3://{bucket}/{key}")
    print(f"  SHA-256 : {digest}")

    with open(file_path, "rb") as fh:
        s3.upload_fileobj(fh, bucket, key, Callback=_Progress(size))

    print("\n  Uploaded successfully.")
    return digest


# ── File discovery ─────────────────────────────────────────────────────────────


def _find_artifacts(search_dir: Path) -> list[Path]:
    pattern = str(search_dir / "fo-artifacts-*.zip")
    matches = sorted(glob.glob(pattern))
    if not matches:
        matches = sorted(glob.glob(str(search_dir / "*.zip")))
    return [Path(m) for m in matches]


# ── Entry point ───────────────────────────────────────────────────────────────


def main() -> None:
    presigned_mode = bool(PRESIGNED_URLS)
    creds_mode = bool(ENDPOINT and ACCESS_KEY and SECRET_KEY and BUCKET)

    if not presigned_mode and not creds_mode:
        print(
            "ERROR: Script is not configured. "
            "Download a fresh copy from ForensicsOperator → Collector.",
            file=sys.stderr,
        )
        sys.exit(1)

    parser = argparse.ArgumentParser(
        description="Upload fo-harvester artifacts to S3-compatible evidence storage."
    )
    parser.add_argument(
        "--file",
        metavar="PATH",
        nargs="+",
        action="append",
        help="Files to upload — space-separated or repeated: --file a.zip b.zip",
    )
    parser.add_argument(
        "--dir",
        metavar="DIR",
        default="./output",
        help="Directory to scan for fo-artifacts-*.zip (default: ./output)",
    )
    if not presigned_mode:
        parser.add_argument(
            "--prefix",
            metavar="PREFIX",
            default="",
            help="S3 key prefix (sub-folder inside the bucket)",
        )
    args = parser.parse_args()

    if args.file:
        files = [Path(p) for group in args.file for p in group]
    else:
        files = _find_artifacts(Path(args.dir))
        if not files:
            print(f"No fo-artifacts-*.zip found in {args.dir}/", file=sys.stderr)
            print("Run fo-harvester.py first, or use --file to specify a path.", file=sys.stderr)
            sys.exit(1)

    print("\n─── ForensicsOperator Evidence Uploader ───────────────────────────────")
    if presigned_mode:
        slots = len(PRESIGNED_URLS)
        print(
            f"Mode: pre-signed URLs ({slots} slot{'s' if slots != 1 else ''}, no credentials stored)"
        )
    else:
        print(f"Mode: S3 credentials  →  {ENDPOINT}/{BUCKET}")
    print()

    if presigned_mode:
        slots = len(PRESIGNED_URLS)
        if len(files) > slots:
            print(
                f"WARNING: {len(files)} files found but only {slots} upload slot{'s' if slots != 1 else ''}. "
                f"Extra files will be skipped.",
                file=sys.stderr,
            )
            files = files[:slots]
        for file_path, url in zip(files, PRESIGNED_URLS):
            if not file_path.exists():
                print(f"ERROR: File not found: {file_path}", file=sys.stderr)
                continue
            digest = _upload_presigned(file_path, url)
            print("\n  Chain of custody hash  (record this):")
            print(f"  File   : {file_path.name}")
            print(f"  SHA-256: {digest}")
    else:
        import uuid as _uuid

        s3 = _build_s3_client()
        prefix = getattr(args, "prefix", "").strip("/")
        session_uid = _uuid.uuid4().hex[:8]
        for file_path in files:
            if not file_path.exists():
                print(f"ERROR: File not found: {file_path}", file=sys.stderr)
                continue
            base = f"{prefix}/{session_uid}" if prefix else session_uid
            key = f"{base}/{file_path.name}"
            digest = _upload_credentials(file_path, BUCKET, key, s3)
            print("\n  Chain of custody hash  (record this):")
            print(f"  File   : {file_path.name}")
            print(f"  SHA-256: {digest}")

    print("\n───────────────────────────────────────────────────────────────────────")
    print("Done. Go to ForensicsOperator → S3 Triage browser to import into a case.")


if __name__ == "__main__":
    main()
